# Generated by Django 5.1.3 on 2024-11-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccument',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
